### ISSUE TITLE
portuguese

### ISSUE THREAD

**Issue by danielgandolfi** [mjockers/syuzhet#11]
hi there

whats the best approach to use the portuguese translation of NRC Emotion Lexicon dictionary in functions like get_nrc_sentiment and values?

thank you
daniel

**Comment by mjockers** [comment]
Can you clarify if you already have a Portuguese translation of NRC Emotion Lexicon dictionary that you wish to implement?

**Comment by vtisza** [comment]
The NRC sentiment lexicon is available in several languages on their homepage. Is it possible to somehow use them or even our own lexicon?

Thank You!

Viktor

**Comment by diegocgaona** [comment]
Hi,

I'm interested in use this nice package with portuguese text (particularly to analyse sentiments in Facebook comments from fan pages).

How @vtisza said, the NRC is available in several languages (http://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm).

How we apply this with your package?

Many thanks, Diego.

**Comment by mjockers** [comment]
Hi Diego,
I'm preparing a new version of the package and will explore the possibility of adding support for other language dictionaries.

**Comment by diegocgaona** [comment]
Thanks Matthew! 
:)

**Comment by mjockers** [comment]
I've opened a new issue "Support for user defined sentiment lexicons" to address this matter of multiple language lexicons so I am closing this one.
