### ISSUE TITLE
Support for user defined sentiment lexicons

### ISSUE THREAD

**Issue by mjockers** [mjockers/syuzhet#13]
Right now the package only works with the built in sentiment lexicons.  It makes sense to add functionality that will allows users to work with their own lexicons or with lexicons in other languages.

**Comment by strategist922** [comment]
hope this function could be add asap, I want to help to extend this package to support Chinese Language

**Comment by mjockers** [comment]
I have added a functionality to the get_sentiment function that allows users to pass in a custom lexicon.  I have documented an example of how to do this in the vignette.  This and other changes to support other languages exist only in the latest dev version on GitHub and will need to be tested before posting to CRAN.
