### ISSUE TITLE
get_sentiment output is invisible

### ISSUE THREAD

**Issue by cstubben** [mjockers/syuzhet#14]
Just a minor issue - I was going through the vignette examples and noticed that get_sentiment output is invisible and can only be assigned.  So running the first command returns nothing.

```
get_sentiment("Why is this function invisible?", method="bing")

x <- get_sentiment("Why do I need to create a new object to print", method="bing")
x
[1] -1
```

I think wrapping return(result) in a else{} statement causes this since its not evaluated.

**Comment by mjockers** [comment]
Thanks.  I have updated the function to correct this issue.
