### ISSUE TITLE
Call get_sentiment() method for non-english data 

### ISSUE THREAD

**Issue by nishutayal** [mjockers/syuzhet#16]
I am calling get_sentiment() method for Russian text.  But for 99% data, it returns 0.00 score. only for 2-3 post, which has some english word, it returned positive or negative value.

I tested with all dictionaries "bing","nrc","afinn"," syuzhet" but results are almost same "Zero".

Can you please tell, how to use this method for Russian or other languages content?

**Comment by mjockers** [comment]
Presently there is no support for languages other than English.  See [https://github.com/mjockers/syuzhet/issues/13](https://github.com/mjockers/syuzhet/issues/13)
