### ISSUE TITLE
get_tokens function missing in 3.2.3

### ISSUE THREAD

**Issue by Mavericks334** [mjockers/syuzhet#23]
Hi,

When install syuzhet library for 3.2.3 get_tokens function is missing.

![get_tokens missing](https://user-images.githubusercontent.com/30084130/28183945-6b7be2ec-67df-11e7-979e-b4cf5b0f2d9a.png)

How do i update the same. I tried to copy paste the function and re-zip the file it does not work giving and MD5 Sums error.

Regards,
Ren.

**Comment by mjockers** [comment]
Hi Ren,
That's odd.  It's not clear to me what you are trying to show with attached code, which does not call the get_tokens() function.

**Comment by Mavericks334** [comment]
Hi,

I am trying to call the function in Tableau for sentiment analysis.

Regards
Ren

**Comment by mjockers** [comment]
I don't know why the function would be masked by Tableau.  Perhaps you could try calling it like this syuzhet::get_tokens()

**Comment by Mavericks334** [comment]
In the folder called doc for the package the file named syuzhet-vignette does not have the function get_tokens. I would try calling the same in tableau once again to see if it would work. Thanks.

**Comment by mjockers** [comment]
Thanks for pointing that out about the vignette.  I'll add something in the next update.

**Comment by Mavericks334** [comment]
My Pleasure. Glad to help out :+1:

**Comment by mjockers** [comment]
get_tokens() is already in the vignette.  The function was added and the vignette updated on 6/26/15.  See https://cran.r-project.org/web/packages/syuzhet/vignettes/syuzhet-vignette.html

**Comment by Mavericks334** [comment]
Unfortunately when I check in 3.2.3 it does not reflect could be an issue
with the R version
