### ISSUE TITLE
Using Syuzhet in Spanish

### ISSUE THREAD

**Issue by ktdesignbox** [mjockers/syuzhet#27]
I am using the following code for sentiment analysis. 

alltweets$clean_text <- str_replace_all(alltweets$text, "@\\w+", "")
Sentiment <- get_nrc_sentiment(alltweets$clean_text)
alltweets_senti <- cbind(alltweets, Sentiment)

sentimentTotals <- data.frame(colSums(alltweets_senti[,c(11:18)]))
names(sentimentTotals) <- "count"
sentimentTotals <- cbind("sentiment" = rownames(sentimentTotals), sentimentTotals)
rownames(sentimentTotals) <- NULL

The full version can be found here: http://rpubs.com/cosmopolitanvan/r_isis_tweets_analytics

I have used this and modified it several times without a problem, but I am not sure on how to use it with Spanish. The code from https://github.com/mjockers/syuzhet/blob/master/vignettes/syuzhet-vignette.Rmd does not work for me either. I would be grateful for any guidance, as I am not good with coding.

**Comment by mjockers** [comment]
Hi ktdesignbox,

I just ran the following code successfully:

`# This code loads the Spanish version of Don Quijote and then 
# gets the NRC sentiment for the first three sentences.
path_to_a_text_file <- system.file("extdata", "quijote.txt",package = "syuzhet")
my_text <- get_text_as_string(path_to_a_text_file)
char_v <- get_sentences(my_text)
get_nrc_sentiment(char_v[1:3], language = "spanish")`

If this is not working for you, it is probably because you have not updated to the version of Syuzhet on GitHub.  The CRAN version is still 1.0.1 whereas the version on GitHub is 1.0.3.  

Please try running the code above after installing 1.0.3 via GitHub, as follows:
`devtools::install_github("mjockers/syuzhet")`

**Comment by ktdesignbox** [comment]
I had to install other two packages along with the new version of syuzhet, but now the program shows this message: Warning in install.packages :
  package 鼠ang・is not available (for R version 3.3.1)

My guess is that I need a newer R version?

**Comment by ktdesignbox** [comment]
I have updated the R version and this time the code runs, but it does not detect sentiment, which is suspicious because the sample texts have the words "love" and "hate" in them. 

This is the output:

Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former
> char_v <- get_sentences(my_text)
> get_nrc_sentiment(char_v[1:2], language = "spanish")
  anger anticipation disgust fear joy sadness surprise trust
1     0            0       0    0   0       0        0     0
2     0            0       0    0   0       0        0     0
  negative positive
1        0        0
2        0        0

**Comment by ktdesignbox** [comment]
Finally did it based on the tutorial I mentioned before and with a csv file. The .txt file never worked. The code is: 

alltweets <- read.csv("testwotime.csv", header = TRUE)
alltweets$clean_text <- str_replace_all(alltweets$text, "@\\w+", "")
Sentiment <- get_nrc_sentiment(alltweets$clean_text, language = "spanish")
alltweets_senti <- cbind(alltweets, Sentiment)
View(Sentiment)

**Comment by mjockers** [comment]
Excellent.  Glad it worked for you.

**Comment by PaulaPRamirez** [comment]
Hello, I have just ran this code but in the graph I can only see the xlabels in English and I am not sure if the emotions are being identified correctly in spanish. 


# Vamos a coger las palabras en español del diccionario NRC
nrc <- get_sentiment(tweets_PSOE_limpios$texto_limpio, method="nrc",language="spanish")

# Vamos a usar una muestra de mensajes
mensajes<-sample_n(tweets_PSOE_limpios,
                   100)

# Obtenemos las emociones
emotions <- get_nrc_sentiment(mensajes$texto_limpio,
                              language ="spanish")
emo_bar = colSums(emotions)
emo_sum = data.frame(count=emo_bar, emotion=names(emo_bar))
emo_sum$emotion = factor(emo_sum$emotion, levels=emo_sum$emotion[order(emo_sum$count, decreasing = TRUE)])


# Definir la paleta de colores para las emociones
colores_emociones <- c(
  "positive" = "#F0E68C",
  "negative" = "#AEC6CF",
  "trust" = "#FFC0CB",
  "sadness" = "#FFDAB9",
  "anticipation" = "#98FB98",
  "fear" = "#FFB6C1",
  "joy" = "#87CEFA",
  "anger" = "#B39EB5",
  "surprise" = "#FFDAB9",
  "disgust" = "#E6E6FA"
)


# Crear un gráfico de barras utilizando ggplot2
emociones_PSOE <- ggplot(emo_sum, aes(x = reorder(emotion, -count), y = count, fill = emotion)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = colores_emociones) +
  labs(x = "", y = "Count", title = "Distribución de emociones de los tweets PSOE") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size=12),
        legend.position = "none")
emociones_PSOE


Please, do you know how can I verify which words are being related to which emotions? The results are a little disappointing considering the context. 

Thank you so much !!

**Comment by el-grudge** [comment]
@PaulaPRamirez  strictly speaking, you can find the sentiment values using something like this: 

```
dict <- get_sentiment_dictionary('nrc', language='spanish')
my_example_test <- "La verdad es que estoy muy feliz hoy."
word_l <- strsplit(my_example_test, "[^A-Za-z']+")
dict[dict$word %in% word_l[[1]],]

# output
# lang | word | sentiment | value
# spanish | feliz | positive | 1
# spanish | verdad | positive | 1
# spanish | muy | negative | 1
# spanish | feliz | anticipation | 1
# spanish | feliz | joy | 1
# spanish | muy | sadness | 1
# spanish | feliz | trust | 1
# spanish | verdad | trust | 1
```
Just note that this only works on one sentence at a time, so if you have a large data set you'll need to create a loop and aggregate the results in a dataframe or something.

**Comment by el-grudge** [comment]
It might be an issue with the lexicon, it looks like sentiments can be more pronounced when using a Spanish lexicon (especially negative sentiments). Here's an illustration:

```
my_example_test <- "Comienzo esta historia con una declaración neutral.
    Básicamente, esta es una prueba muy tonta.
    Está probando el paquete Syuzhet usando oraciones cortas y sin sentido.
    La verdad es que estoy muy feliz hoy.
    Finalmente he terminado de escribir este paquete.
    Mañana estaré muy triste.
    No me quedará nada más que hacer.
    Podría enojarme y decidir hacer algo horrible.
    Podría destruir todo el paquete y empezar de cero.
    Por otra parte, podría resultarme satisfactorio haber completado mi primer paquete de R.
    Honestamente, este uso de la transformación de Fourier es bastante elegante.
    ¡Incluso podrías decir que es hermoso!"
char_v <- get_sentences(my_example_test)
get_nrc_sentiment(char_v, language = "spanish")

# output
# anger | anticipation | disgust | fear | joy | sadness | surprise | trust | negative | positive
# -- | -- | -- | -- | -- | -- | -- | -- | -- | --
# 0 | 3 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0
# 0 | 0 | 0 | 0 | 0 | 1 | 0 | 1 | 1 | 0
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1
# 0 | 1 | 0 | 0 | 1 | 1 | 0 | 2 | 1 | 2
# 0 | 1 | 1 | 0 | 1 | 0 | 1 | 1 | 0 | 1
# 1 | 0 | 1 | 2 | 0 | 6 | 0 | 0 | 6 | 0
# 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 1 | 1
# 3 | 0 | 6 | 5 | 0 | 3 | 0 | 0 | 6 | 1
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
# 0 | 0 | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 2
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1
```

Now, here's the English translation of the same text and the sentiment values per each sentence:

```
my_example_text <- "I begin this story with a neutral statement.  
  Basically this is a very silly test.  
  You are testing the Syuzhet package using short, inane sentences.  
  I am actually very happy today. 
  I have finally finished writing this package.  
  Tomorrow I will be very sad. 
  I won't have anything left to do. 
  I might get angry and decide to do something horrible.  
  I might destroy the entire package and start from scratch.  
  Then again, I might find it satisfying to have completed my first R package. 
  Honestly this use of the Fourier transformation is really quite elegant.  
  You might even say it's beautiful!"
char_v <- get_sentences(my_example_test)
get_nrc_sentiment(char_v, language = "english")

# output
# anger | anticipation | disgust | fear | joy | sadness | surprise | trust | negative | positive
# -- | -- | -- | -- | -- | -- | -- | -- | -- | --
# 
# 0 | 1 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
# 1 | 0 | 1 | 1 | 0 | 1 | 0 | 0 | 1 | 0
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
# 1 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 1 | 0
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 1
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
# 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
```

Notice how the values in English are always 0/1 whereas in Spanish they can go up as high as 6. I don't have a clear explanation for why that is, and maybe it's just a quirk of this particular example, but maybe look around and see if you can find another lexicon.

**Comment by PaulaPRamirez** [comment]
Thank you so much!! I will try to find another lexicon and see if it works better with Spanish.

**Comment by exetrujillo** [comment]
Did you find another lexicon, I'm just trying to do the same thing, but until now, the best method for me is to translate to english with the model Helsinki-NLP/opus-mt-es-en, and then using j-hartmann/emotion-english-distilroberta-base. It became impossible for me to do it using only R.
