### ISSUE TITLE
Adding NRC kind of Dictionaries 

### ISSUE THREAD

**Issue by breyesr** [mjockers/syuzhet#32]
Hi,

I've been using syuzhet and got to say it's just awesome.  What I would like to add is my own dictionary in a NRC kind of way with my own sentiments and values.

I'm kind of new to R and I tried to replicate the get_nrc_sentiment() and get_nrc_values in order to acomplish getting my own dictionary. I came up with something like this:

 `get_custom_sentiment <- function(char_v, cl=NULL,  lowercase = TRUE, myDictionary){
  if (!is.character(char_v)) stop("Data must be a character vector.")
  if(!is.null(cl) && !inherits(cl, 'cluster')) stop("Invalid Cluster")
  #lexicon <- dplyr::filter_(nrc, ~lang == language) #I commented this since I wanted my own dictionary
  if(lowercase){
    char_v <- tolower(char_v)
  }
  word_l <- strsplit(char_v, "[^A-Za-z']+")
  
  if(is.null(cl)){
    nrc_data <- lapply(word_l, get_custom_values, lexicon = myDictionary)
  }
  else{
    nrc_data <- parallel::parLapply(cl=cl, word_l, lexicon = myDictionary, get_custom_values(myDictionary))
  }
  
  result_df <- as.data.frame(do.call(rbind, nrc_data), stringsAsFactors=F)
  #reorder the columns
  my_col_order <- c(
    "anger", 
    "anticipation", 
    "disgust", 
    "fear", 
    "joy", 
    "sadness", 
    "surprise", 
    "trust", 
    "negative", 
    "positive"
  )
  result_df[, my_col_order]
}`

And for getting the values:

`get_custom_values <- function(word_vector,lexicon = NULL){
  #if (is.null(lexicon)) {
  #lexicon <- dplyr::filter_(nrc, ~lang == language)
  #} Again, commented this since I want my own Dictionary
   if (! all(c("word", "sentiment", "value") %in% names(lexicon)))
      stop("lexicon must have a 'word', a 'sentiment' and a 'value' field")
  
  data <- dplyr::filter_(myDictionary, ~word %in% word_vector)
  data <- dplyr::group_by_(data, ~sentiment)
  data <- dplyr::summarise_at(data, "value", sum)
  
  all_sent <- unique(myDictionary$sentiment)
  sent_present <- unique(data$sentiment)
  sent_absent  <- setdiff(all_sent, sent_present)
  if (length(sent_absent) > 0) {
    missing_data <- dplyr::data_frame(sentiment = sent_absent, value = 0)
    data <- rbind(data, missing_data)
  }
  tidyr::spread_(data, "sentiment", "value")
}`

If I pass the dictionary directly into the function code (not as a variable) the code works, but if I pass it as a variable I get this error: 

_Error in get_custom_sentiment(DB$text, feelings) : 
  Invalid Cluster_

My guess is there is something in how I format de custom dictionary that doesn't let the function find the clusters in this line 
` if(!is.null(cl) && !inherits(cl, 'cluster')) stop("Invalid Cluster")` 

But also if that was the case why does it work if I put the dictionary directly inside the function. 
I hope this makes sense and that you could point me in the right direction to work on this.

**Comment by mjockers** [comment]
Hi, Glad you like the package.  There is already functionality for adding a custom sentiment lexicon in the get_sentiment function.  Use the "lexicon" argument. Is that all you need, or do you need the emotional types as in NRC?

**Comment by breyesr** [comment]
Hi, thanks for your time! I saw the custom sentiment but I also need the emotional types, that's why I'm  trying to figure out how the function was built. Let's say for example that I want to analyze some NPS data, I'd like to graph "sentiments" or topics relate to price, service, etc.

Something like this:

![imagen](https://user-images.githubusercontent.com/43413866/68707940-4ddfe080-0558-11ea-830a-94491eb881bb.png)

**Comment by mjockers** [comment]
You should be able to call get_nrc_sentiment() function using the lexicon argument and your own custom dictionary as a data frame.  To see how that dictionary must be formatted, you can use: nrc_dict <- get_sentiment_dictionary("nrc").  If you then look at the dictionary (nrc_dict) in depth (i.e. unique(nrc_dict$sentiment)), you will see, for example, that the "sentiment" column of the data frame contains the following values: "positive", "negative",  "anger", "anticipation", "disgust",  "fear", "joy", "sadness", "surprise", "trust".  You would need to build a similarly formatted dictionary and then send it to the get_nrc_sentiment() function as the lexicon argument.

**Comment by AmauryVanEspen** [comment]
Hello @mjockers 
I was not able to add the FEEL dictionnary (from http://www.lirmm.fr/~abdaoui/FEEL.html)
there are also quite intereting resources behind BNOSA to bind as sentiment dictionnary (https://www.bnosac.be/index.php/blog/85-you-did-a-sentiment-analysis-with-tidytext-but-you-forgot-to-do-dependency-parsing-to-answer-why-is-something-positive-negative)

Could you provide help in integrating the FEEL dictionary (French) ? Thank you

Amaury

**Comment by LuciaEspasandin** [comment]
Hello @mjockers ,

I would like to add something to this discussion because we are experiencing the same problem as @breyesr .
We created a new own costum dictionary using the same format of the NRC dictionary downloaded from the package.
However we were not able to run the get_nrc_sentiment() by calling the updated dictionary in the "lexicon" argument.

We got the following error:

**Error in get_nrc_sentiment(angling_comments, lexicon = new_dictionary) :
              unused argument (lexicon =  new_dictionary)**

We think that the reason of the error is that the argument "lexicon" is not an argument of the function "get_nrc_sentiment".
It would be great to find a solution to this problem.

Thank you in advance,

Lucía

**Comment by mjockers** [comment]
@LuciaEspasandin Thanks for posting this.  

I realize now that my previous answer to @breyesr was not correct.  I have just updated the package on github (not yet on CRAN) and revised the get_nrc_sentiment() function to provide the requested functionality.  Please read the new documentation for the function and see the included example.  Should be clear how to format your custom lexicon to work with the revised function. Remember you will need to install the package from github to get the updates. i.e. . . .

# install.packages("devtools")
devtools::install_github("mjockers/syuzhet")

RE @AmauryVanEspen 's question... sorry, this link is broken: http://www.lirmm.fr/~abdaoui/FEEL.html
