### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by ThisIsJohnnyLau** [mjockers/syuzhet#35]
Hi!

Thanks for producing and sharing a great package.

I had these warnings come up that you might consider in any new releases.

`filter_()` is deprecated as of dplyr 0.7.0.
Please use `filter()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.

Call `lifecycle::last_warnings()` to see where this warning was generated.`group_by_()` is deprecated as of dplyr 0.7.0.
Please use `group_by()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.

Call `lifecycle::last_warnings()` to see where this warning was generated.`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.

Thanks again.
Johnny

**Comment by mjockers** [comment]
Hi Johnny,
These issues were resolved last month in the most current version posted here on github.  I have not pushed this version to CRAN yet, but if you use:
devtools::install_github("mjockers/syuzhet")
You should have the most recent version that will not have these issues.

**Comment by ThisIsJohnnyLau** [comment]
Hi Matthew,

Genius!  Thanks for following up.

Kind regards,
Johnny.
