### ISSUE TITLE
Example in `get_transformed_values()` returns only NA

### ISSUE THREAD

**Issue by lmullen** [mjockers/syuzhet#5]
Running `example(get_transformed_values)` returns only a vector of one hundred `NA`s. I suspect that the problem is that the example text has fewer than 100 sentences. One possible fix is to use Joyce's *Portrait* that is now in `inst/extdata`.

**Comment by mjockers** [comment]
You are on the right track, but it's really because the low_pass_size arg is smaller than the number of items in raw_values.  I'm adding logic to correct it now. . .
