### ISSUE TITLE
What is the distinction between `scale_vals` and `scale_range`?

### ISSUE THREAD

**Issue by lmullen** [mjockers/syuzhet#6]
@mjockers:

Can you explain the distinction between calling `get_transformed_values()` with `scale_vals = TRUE`, `scale_range = TRUE`, and both of those being false? Below are three plots of the [same text](https://archive.org/details/101178399.nlm.nih.gov) using the different values. The shape of the curve is the same, as expected, but the zero moves up and down. I understand how the scales are calculated. But what difference does this make for (1) interpreting the plot of a single text and (2) for comparing among the texts in a corpus?  

Unscaled:

![101178399 nlm nih gov-101178399_djvu-un](https://cloud.githubusercontent.com/assets/183672/6195637/19373efc-b39e-11e4-9d82-7b4a6cce0360.png)

Scaled with `scale_vals = TRUE`:

![101178399 nlm nih gov-101178399_djvu-vals](https://cloud.githubusercontent.com/assets/183672/6195667/28ee1df2-b39e-11e4-9e9f-7800c982c574.png)

Scaled with `scale_range = TRUE`:
![101178399 nlm nih gov-101178399_djvu-range](https://cloud.githubusercontent.com/assets/183672/6195627/09c3f942-b39e-11e4-9b23-056e3c5a22b8.png)

**Comment by mjockers** [comment]
Added explanation to function documentation as follows:
@param scale_range Logical determines whether or not to scale the values from -1 to +1.  Default = FALSE.  If set to TRUE, the lowest value in the vector will be set to -1 and the highest values set to +1 and all the values scaled accordingly in between.
#'  @param scale_vals Logical determines whether or not to normalize the values using the scale function  Default = FALSE.  If TRUE, values will be scaled by subtracting the means and scaled by dividing by their standard deviations.  See ?scale
