### ISSUE TITLE
Considering negators in sentiment 

### ISSUE THREAD

**Issue by trinker** [mjockers/syuzhet#7]
Matt thanks for putting this package together.  I was testing some of the different functionalities and I noticed that maybe negators (e.g., *not*, *never*).  Maybe I'm not understanding the use or this is beyond the scope of the package or not a part of the algorithms you've implemented.  

Here are some examples demonstrating what I'm talking about.  I'd expect to see negative sentiment here.

```r
print(get_sentiment("John is never successful at tennis."))
```

```r
setNames(lapply(c("afinn", "bing", "nrc"), function(x) {
    try(get_sentiment("this is not good at all", method=x))
}), c("afinn", "bing", "nrc"))
```

```r
$afinn
[1] 3

$bing
[1] 1

$nrc
[1] 1
```

**Comment by mjockers** [comment]
Right, this is a downside to all of the dictionary-lookup based approaches (afinn, bing, and nrc).  They don't grapple with negation.  Do check out the citations to these dictionaries in the documentation for the get_sentiment() function.  When it comes to grappling with negation, the Stanford sentiment tagger is best, so I'd urge you to give it a try.  I've written a function for accessing the Stanford tool via Syuzhet, but honestly it is just a hack that passes a system command to call the parser.  If you are comfortable with Java and/or the command line, you could just go straight to the coreNLP package (http://nlp.stanford.edu/software/corenlp.shtml).  FWIW, I have found that in long form fiction (my primary area of research) negation of the sort you describe is rarely sustained; that is, it tends to be rare enough that the overall sentiment balances out over multiple sentences.  If you are looking for the best sentence level sentiment tagger, than coreNLP is your winner.

**Comment by trinker** [comment]
Thanks for getting back to me.  Much appreciated.  I was surface level playing and didn't try that method yet (as it takes a little more work out of the box)  so I'll give the coreNLP method a try.  The refs look useful too.  I'm familiar with Hu and Liu's work but not the other pieces.  

PS congrats on the first package.
