### ISSUE TITLE
Rely on StanfordCoreNLP package?

### ISSUE THREAD

**Issue by lmullen** [mjockers/syuzhet#8]
Right now syuzhet calls StanfordCoreNLP as a `system()` command. In principle it is better to use an `rJava` wrapper. There is a `StanfordCoreNLP` package already: it's just not hosted at CRAN because the models are too big. You can [find the package at DataCube](http://datacube.wu.ac.at/src/contrib/). And it can be installed with the following command:

```
install.packages("StanfordCoreNLP", repos = "http://datacube.wu.ac.at/", type = "source")
```

See the documentation here: `?StanfordCoreNLP_Pipeline`. It's not a particularly well designed API, but it wouldn't be too hard to write some accessor functions to clean things up. It gives access to the sentiment parser.

I'd suggest re-writing `get_stanford_sentiment()` to rely on this package. Unfortunately there is no good way to express dependencies on packages which are not on CRAN. I had this problem with the `gender` package since CRAN won't take data packages above 5MB. So I wrote a function which checks to see if the `genderdata` package is installed, and if not, prompts the user to install it. You could do the same thing to check if the `StanfordCoreNLP` package is installed. Here is the [function from `gender`](https://github.com/ropensci/gender/blob/master/R/install-genderdata-package.R).

**Comment by mjockers** [comment]
Yes.  The current implementation is a lazy hack.  It's on my list to work on this.

**Comment by mjockers** [comment]
. . .and I don't think that the hack works at all on a Windows platform. . .

**Comment by trinker** [comment]
I prefer the hack.  Using the `rJava` often runs into memory problems.  This doesn't seem to be an issue in the `system` approach.  On Windows it doesn't work but I borrowed heavily from your approach to make this stanford sentiment packages.  https://github.com/trinker/stansent  Feel free to borrow back to make sure it works on Windows.

**Comment by mjockers** [comment]
Closing this because want to avoid the rJava package that seems to be a constant problem.  Will look to improve the hack in the future, perhaps via trinker's https://github.com/trinker/stansent
