### ISSUE TITLE
get_percentage_values occasionally returns 101 results

### ISSUE THREAD

**Issue by bmschmidt** [mjockers/syuzhet#9]
On my architecture (Macbook air OS X 10.9, full system profile on request), the function get_percentage_values occasionally returns 101 results instead of 100: at lengths 201, 203, 205, etc. This makes it hard to directly compare results.

The distribution is actually regular in kind of a pretty way if you plot it: groups of 4,3,2,1 progressively farther apart as n gets higher. Maybe a floating point issue of some sort? It seems that 100.00000 is occasionally rounding up to 101.

In any case, using `cut` instead of `seq_along` and `ceiling` fixes it--I'm posting a patch.

``` {r}
library(syuzhet)
lengths = sapply(200:1500,function(n) {
  dummy_sentiment_vector = sample(c(-1,0,1),n,replace=T) 
  length(get_percentage_values(dummy_sentiment_vector))
})
plot(200:1500,lengths)
```

![image](https://cloud.githubusercontent.com/assets/1110758/6967116/5c2cb0e0-d92b-11e4-867a-4f5fb1722100.png)

**Comment by mjockers** [comment]
Good fix Ben.  Was not even aware of the "cut" function.
